# Generated by Django 5.1.3 on 2024-12-11 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='category.category'),
            preserve_default=False,
        ),
    ]
